// Copyright https://github.com/MothCocoon/FlowGraph/graphs/contributors

#pragma once

#include "FlowNode_CustomEventBase.h"
#include "Interfaces/FlowNodeWithExternalDataPinSupplierInterface.h"
#include "Interfaces/FlowDataPinGeneratorNodeInterface.h"
#include "Types/FlowDataPinProperties.h"
#include "FlowNode_CustomInput.generated.h"

/**
 * Triggers output upon activation of Input (matching this EventName) on the SubGraph node containing this graph.
 * Supports data pin properties that are passed from the parent SubGraph node.
 */
UCLASS(NotBlueprintable, meta = (DisplayName = "Custom Input"))
class FLOW_API UFlowNode_CustomInput
	: public UFlowNode_CustomEventBase
	, public IFlowNodeWithExternalDataPinSupplierInterface
	, public IFlowDataPinGeneratorNodeInterface
{
	GENERATED_UCLASS_BODY()

	friend class UFlowAsset;

protected:

	UPROPERTY(EditAnywhere, Category = "DataPins", DisplayName = Properties)
	TArray<FFlowNamedDataPinOutputProperty> OutputProperties;

	UPROPERTY(Transient)
	TScriptInterface<IFlowDataPinValueSupplierInterface> FlowDataPinValueSupplierInterface;

public:

	// UFlowNode
	virtual void ExecuteInput(const FName& PinName) override;
	virtual void PostEditImport() override;
	// --

	// IFlowNodeWithExternalDataPinSupplierInterface
	virtual void SetDataPinValueSupplier(IFlowDataPinValueSupplierInterface* DataPinValueSupplier) override;
	virtual IFlowDataPinValueSupplierInterface* GetExternalDataPinSupplier() const override { return FlowDataPinValueSupplierInterface.GetInterface(); }
#if WITH_EDITOR
	virtual bool TryAppendExternalInputPins(TArray<FFlowPin>& InOutPins) const override;
#endif
	// --

	// Must implement TrySupplyDataAs... for every EFlowPinType
	FLOW_ASSERT_ENUM_MAX(EFlowPinType, 16);

	// IFlowDataPinValueSupplierInterface
	virtual FFlowDataPinResult_Bool TrySupplyDataPinAsBool_Implementation(const FName& PinName) const override;
	virtual FFlowDataPinResult_Int TrySupplyDataPinAsInt_Implementation(const FName& PinName) const override;
	virtual FFlowDataPinResult_Float TrySupplyDataPinAsFloat_Implementation(const FName& PinName) const override;
	virtual FFlowDataPinResult_Name TrySupplyDataPinAsName_Implementation(const FName& PinName) const override;
	virtual FFlowDataPinResult_String TrySupplyDataPinAsString_Implementation(const FName& PinName) const override;
	virtual FFlowDataPinResult_Text TrySupplyDataPinAsText_Implementation(const FName& PinName) const override;
	virtual FFlowDataPinResult_Enum TrySupplyDataPinAsEnum_Implementation(const FName& PinName) const override;
	virtual FFlowDataPinResult_Vector TrySupplyDataPinAsVector_Implementation(const FName& PinName) const override;
	virtual FFlowDataPinResult_Rotator TrySupplyDataPinAsRotator_Implementation(const FName& PinName) const override;
	virtual FFlowDataPinResult_Transform TrySupplyDataPinAsTransform_Implementation(const FName& PinName) const override;
	virtual FFlowDataPinResult_GameplayTag TrySupplyDataPinAsGameplayTag_Implementation(const FName& PinName) const override;
	virtual FFlowDataPinResult_GameplayTagContainer TrySupplyDataPinAsGameplayTagContainer_Implementation(const FName& PinName) const override;
	virtual FFlowDataPinResult_InstancedStruct TrySupplyDataPinAsInstancedStruct_Implementation(const FName& PinName) const override;
	virtual FFlowDataPinResult_Object TrySupplyDataPinAsObject_Implementation(const FName& PinName) const override;
	virtual FFlowDataPinResult_Class TrySupplyDataPinAsClass_Implementation(const FName& PinName) const override;
	// --

#if WITH_EDITOR
public:
	virtual FText GetNodeTitle() const override;

	// IFlowContextPinSupplierInterface
	virtual bool SupportsContextPins() const override { return Super::SupportsContextPins() || !OutputProperties.IsEmpty(); }
	// --

	// UObject
	virtual void PostEditChangeChainProperty(FPropertyChangedChainEvent& PropertyChangedEvent) override;
	// --

	// IFlowDataPinGeneratorNodeInterface
	virtual void AutoGenerateDataPins(TMap<FName, FName>& PinNameToBoundPropertyMap, TArray<FFlowPin>& InputDataPins, TArray<FFlowPin>& OutputDataPins) const override;
	// --
#endif

protected:
	virtual bool TryFindPropertyByRemappedPinName(
		const FName& RemappedPinName,
		const FProperty*& OutFoundProperty,
		TInstancedStruct<FFlowDataPinProperty>& OutFoundInstancedStruct,
		EFlowDataPinResolveResult& InOutResult) const override;
};
