// Copyright https://github.com/MothCocoon/FlowGraph/graphs/contributors

#include "Nodes/Graph/FlowNode_CustomInput.h"
#include "FlowSettings.h"
#include "Types/FlowDataPinProperties.h"

#include UE_INLINE_GENERATED_CPP_BY_NAME(FlowNode_CustomInput)

#define LOCTEXT_NAMESPACE "FlowNode_CustomInput"

UFlowNode_CustomInput::UFlowNode_CustomInput(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
{
	InputPins.Empty();
}

void UFlowNode_CustomInput::ExecuteInput(const FName& PinName)
{
	TriggerFirstOutput(true);
}

void UFlowNode_CustomInput::PostEditImport()
{
	EventName = NAME_None;
}

void UFlowNode_CustomInput::SetDataPinValueSupplier(IFlowDataPinValueSupplierInterface* DataPinValueSupplier)
{
	FlowDataPinValueSupplierInterface = Cast<UObject>(DataPinValueSupplier);
}

#if WITH_EDITOR

FText UFlowNode_CustomInput::GetNodeTitle() const
{
	if (!EventName.IsNone() && UFlowSettings::Get()->bUseAdaptiveNodeTitles)
	{
		return FText::Format(LOCTEXT("CustomInputTitle", "{0} Input"), {FText::FromString(EventName.ToString())});
	}

	return Super::GetNodeTitle();
}

bool UFlowNode_CustomInput::TryAppendExternalInputPins(TArray<FFlowPin>& InOutPins) const
{
	for (const FFlowNamedDataPinOutputProperty& DataPinProperty : OutputProperties)
	{
		if (DataPinProperty.IsValid())
		{
			InOutPins.AddUnique(DataPinProperty.CreateFlowPin());
		}
	}

	return !OutputProperties.IsEmpty();
}

void UFlowNode_CustomInput::AutoGenerateDataPins(TMap<FName, FName>& PinNameToBoundPropertyMap, TArray<FFlowPin>& InputDataPins, TArray<FFlowPin>& OutputDataPins) const
{
	for (const FFlowNamedDataPinOutputProperty& DataPinProperty : OutputProperties)
	{
		if (DataPinProperty.IsValid())
		{
			PinNameToBoundPropertyMap.Add(DataPinProperty.Name, DataPinProperty.Name);
			OutputDataPins.AddUnique(DataPinProperty.CreateFlowPin());
		}
	}
}

void UFlowNode_CustomInput::PostEditChangeChainProperty(FPropertyChangedChainEvent& PropertyChainEvent)
{
	Super::PostEditChangeChainProperty(PropertyChainEvent);

	if (PropertyChainEvent.PropertyChain.Num() == 0)
	{
		return;
	}

	auto& Property = PropertyChainEvent.PropertyChain.GetActiveMemberNode()->GetValue();

	if (PropertyChainEvent.ChangeType == EPropertyChangeType::ValueSet &&
		Property->GetFName() == GET_MEMBER_NAME_CHECKED(FFlowDataPinOutputProperty_Enum, EnumName))
	{
		for (FFlowNamedDataPinOutputProperty& OutputProperty : OutputProperties)
		{
			if (!OutputProperty.IsValid())
			{
				continue;
			}

			const FFlowDataPinProperty& FlowDataPinProperty = OutputProperty.DataPinProperty.Get();

			if (FlowDataPinProperty.GetFlowPinType() == EFlowPinType::Enum)
			{
				FFlowDataPinOutputProperty_Enum& EnumProperty = OutputProperty.DataPinProperty.GetMutable<FFlowDataPinOutputProperty_Enum>();
				EnumProperty.OnEnumNameChanged();
			}

			FLOW_ASSERT_ENUM_MAX(EFlowPinType, 16);
		}
	}

	constexpr EPropertyChangeType::Type RelevantChangeTypesForReconstructionMask =
		EPropertyChangeType::Unspecified |
		EPropertyChangeType::ArrayAdd |
		EPropertyChangeType::ArrayRemove |
		EPropertyChangeType::ArrayClear |
		EPropertyChangeType::ValueSet |
		EPropertyChangeType::Redirected |
		EPropertyChangeType::ArrayMove;

	const uint32 PropertyChangedTypeFlags = (PropertyChainEvent.ChangeType & RelevantChangeTypesForReconstructionMask);
	const bool bIsRelevantChangeTypeForReconstruction = PropertyChangedTypeFlags != 0;
	const bool bChangedOutputProperties = Property->GetFName() == GET_MEMBER_NAME_CHECKED(UFlowNode_CustomInput, OutputProperties);
	if (bIsRelevantChangeTypeForReconstruction && bChangedOutputProperties)
	{
		OnReconstructionRequested.ExecuteIfBound();
	}
}

#endif // WITH_EDITOR

bool UFlowNode_CustomInput::TryFindPropertyByRemappedPinName(
	const FName& RemappedPinName,
	const FProperty*& OutFoundProperty,
	TInstancedStruct<FFlowDataPinProperty>& OutFoundInstancedStruct,
	EFlowDataPinResolveResult& InOutResult) const
{
	for (const FFlowNamedDataPinOutputProperty& NamedProperty : OutputProperties)
	{
		if (NamedProperty.Name == RemappedPinName && NamedProperty.IsValid())
		{
			OutFoundInstancedStruct = NamedProperty.DataPinProperty;
			return true;
		}
	}

	return Super::TryFindPropertyByPinName(RemappedPinName, OutFoundProperty, OutFoundInstancedStruct, InOutResult);
}

// Must implement TrySupplyDataPinAs... for every EFlowPinType
FLOW_ASSERT_ENUM_MAX(EFlowPinType, 16);

#define IMPLEMENT_CUSTOM_INPUT_DATA_PIN_SUPPLY(TypeName) \
FFlowDataPinResult_##TypeName UFlowNode_CustomInput::TrySupplyDataPinAs##TypeName##_Implementation(const FName& PinName) const \
{ \
	if (FlowDataPinValueSupplierInterface) \
	{ \
		FFlowDataPinResult_##TypeName SuppliedResult = IFlowDataPinValueSupplierInterface::Execute_TrySupplyDataPinAs##TypeName(FlowDataPinValueSupplierInterface.GetObject(), PinName); \
		if (SuppliedResult.Result == EFlowDataPinResolveResult::Success) \
		{ \
			return SuppliedResult; \
		} \
	} \
	return Super::TrySupplyDataPinAs##TypeName##_Implementation(PinName); \
}

IMPLEMENT_CUSTOM_INPUT_DATA_PIN_SUPPLY(Bool)
IMPLEMENT_CUSTOM_INPUT_DATA_PIN_SUPPLY(Int)
IMPLEMENT_CUSTOM_INPUT_DATA_PIN_SUPPLY(Float)
IMPLEMENT_CUSTOM_INPUT_DATA_PIN_SUPPLY(Name)
IMPLEMENT_CUSTOM_INPUT_DATA_PIN_SUPPLY(String)
IMPLEMENT_CUSTOM_INPUT_DATA_PIN_SUPPLY(Text)
IMPLEMENT_CUSTOM_INPUT_DATA_PIN_SUPPLY(Enum)
IMPLEMENT_CUSTOM_INPUT_DATA_PIN_SUPPLY(Vector)
IMPLEMENT_CUSTOM_INPUT_DATA_PIN_SUPPLY(Rotator)
IMPLEMENT_CUSTOM_INPUT_DATA_PIN_SUPPLY(Transform)
IMPLEMENT_CUSTOM_INPUT_DATA_PIN_SUPPLY(GameplayTag)
IMPLEMENT_CUSTOM_INPUT_DATA_PIN_SUPPLY(GameplayTagContainer)
IMPLEMENT_CUSTOM_INPUT_DATA_PIN_SUPPLY(InstancedStruct)
IMPLEMENT_CUSTOM_INPUT_DATA_PIN_SUPPLY(Object)
IMPLEMENT_CUSTOM_INPUT_DATA_PIN_SUPPLY(Class)

#undef IMPLEMENT_CUSTOM_INPUT_DATA_PIN_SUPPLY
#undef LOCTEXT_NAMESPACE
