const assert = require('assert');
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'public', 'index.html'), 'utf8');
const css = fs.readFileSync(path.join(root, 'public', 'styles.css'), 'utf8');
const js = fs.readFileSync(path.join(root, 'public', 'app.js'), 'utf8');
const storyHtml = fs.readFileSync(path.join(root, 'public', 'story.html'), 'utf8');
const storyCss = fs.readFileSync(path.join(root, 'public', 'story.css'), 'utf8');
const storyJs = fs.readFileSync(path.join(root, 'public', 'story.js'), 'utf8');

assert.ok(html.includes('id="contextMenu"'), 'page should include a custom right-click node menu');
assert.ok(!html.includes('id="edgeModeButton"'), 'left sidebar should not require a start-connection mode button');
assert.ok(js.includes('startCanvasPan'), 'app should support middle/right mouse canvas panning');
assert.ok(js.includes('centerCanvasView'), 'app should center the canvas view');
assert.ok(js.includes('applyCanvasPan'), 'app should use a dedicated canvas pan helper');
assert.ok(js.includes('undoStack') && js.includes('redoStack'), 'app should maintain undo and redo stacks');
assert.ok(js.includes('undoGraphChange') && js.includes('redoGraphChange'), 'app should expose undo and redo actions');
assert.ok(js.includes("event.key.toLowerCase() === 'z'") && js.includes("event.key.toLowerCase() === 'y'"), 'app should support keyboard undo and redo');
assert.ok(html.includes('id="undoButton"') && html.includes('id="redoButton"'), 'page should include undo and redo buttons');
assert.ok(js.includes('startPinConnection') && js.includes('finishPinConnection'), 'nodes should connect by dragging pins');
assert.ok(js.includes('showConnectionMenu'), 'dropping a pin connection on empty canvas should open the node menu');
assert.ok(js.includes('connection-preview'), 'pin dragging should render a preview connection');
assert.ok(js.includes('edgeEndpointPoints'), 'saved edges should render between pin endpoints');
assert.ok(js.includes('pinPoint(source') && js.includes('pinPoint(target'), 'edge paths should use node pin coordinates');
assert.ok(!js.includes('return makePathBetweenPoints(centerOf(source), centerOf(target))'), 'edges should not connect node centers after pins exist');
assert.ok(js.includes('focusSelectedOrAllNodes') && js.includes('frameNodes'), 'F should focus selected nodes and all nodes');
assert.ok(js.includes("event.key.toLowerCase() === 'f'"), 'app should handle F as a focus shortcut');
assert.ok(!js.includes('Math.max(0, state.drag.originalX'), 'node dragging should allow negative coordinates on a free canvas');
assert.ok(js.includes('selectedNodeIds'), 'app should track multi-node selection');
assert.ok(js.includes('startBoxSelection') && js.includes('updateBoxSelection') && js.includes('finishBoxSelection'), 'canvas should support left-drag box selection');
assert.ok(js.includes('nodesInsideSelectionBox'), 'box selection should resolve enclosed nodes');
assert.ok(js.includes('selectionBox'), 'box selection should render a selection rectangle');
assert.ok(js.includes('nodeClipboard'), 'app should maintain a node clipboard for copy and paste');
assert.ok(js.includes('copySelectedNodes') && js.includes('pasteCopiedNodes') && js.includes('duplicateSelectedNodes'), 'app should copy, paste, and duplicate selected nodes');
assert.ok(js.includes('copyInternalEdges'), 'copying multiple nodes should preserve edges between copied nodes');
assert.ok(js.includes("event.key.toLowerCase() === 'c'") && js.includes("event.key.toLowerCase() === 'v'") && js.includes("event.key.toLowerCase() === 'd'"), 'app should support Ctrl+C, Ctrl+V, and Ctrl+D');
assert.ok(js.includes('node-delete-button'), 'nodes should include an inline red delete button');
assert.ok(js.includes('node-pin'), 'nodes should include connection pins');
assert.ok(css.includes('.context-menu'), 'context menu should have styles');
assert.ok(css.includes('.node-delete-button'), 'node delete button should have styles');
assert.ok(css.includes('.node-pin'), 'node pins should have styles');
assert.ok(css.includes('.connection-preview'), 'connection preview should have styles');
assert.ok(css.includes('.canvas-wrap.is-panning'), 'canvas panning should have visual cursor feedback');
assert.ok(css.includes('.canvas-wrap.is-connecting'), 'pin connection should have visual cursor feedback');
assert.ok(css.includes('.canvas-wrap.is-selecting'), 'box selection should have visual cursor feedback');
assert.ok(css.includes('.selection-box'), 'box selection rectangle should have styles');
assert.ok(css.includes('.history-row'), 'undo and redo controls should have styles');
assert.ok(storyHtml.includes('id="syncMetadataButton"'), 'story editor should expose metadata sync');
assert.ok(storyHtml.includes('id="syncUeMetadataButton"'), 'story editor should expose UE metadata sync');
assert.ok(storyHtml.includes('id="undoButton"') && storyHtml.includes('id="redoButton"'), 'story editor should expose undo and redo buttons');
assert.ok(storyHtml.includes('id="ueDryRunButton"') && storyHtml.includes('id="ueApplyButton"'), 'story editor should expose UE sync actions');
assert.ok(storyJs.includes('/api/story/sync-metadata'), 'story editor should call metadata sync endpoint');
assert.ok(storyJs.includes('/api/story/sync-ue-metadata'), 'story editor should call UE metadata sync endpoint');
assert.ok(storyJs.includes('/api/story/import-ue'), 'story editor should call UE import endpoint');
assert.ok(storyJs.includes('multiChoiceInput'), 'story editor should support multi-choice dropdown fields');
assert.ok(storyJs.includes('comboInput'), 'story editor should support editable dropdown fields');
assert.ok(storyJs.includes('TIMELINE_PRESETS'), 'story editor should expose managed timeline presets');
assert.ok(storyJs.includes('自定义时间线 ID'), 'timeline field should allow adding custom timeline ids');
assert.ok(storyJs.includes('剧情点类型') && storyJs.includes('动作类型'), 'story point editor should use Chinese field labels');
assert.ok(storyJs.includes('对话 / 提示框') && storyJs.includes('仅触发一次'), 'story point dropdowns should show Chinese labels while keeping engine values');
assert.ok(storyJs.includes('FIELD_HELP') && storyJs.includes('EncounterId / EM_') && storyJs.includes('流程图资产 / EG_'), 'story editor should describe core story asset fields');
assert.ok(storyJs.includes('caption.title = help'), 'story field labels should expose hover help text');
assert.ok(storyJs.includes('演出需求'), 'story point editor should expose per-point staging requirements');
assert.ok(storyJs.includes('JSON.stringify(state.segment.states'), 'advanced state fields should preserve structured JSON');
assert.ok(storyHtml.includes('id="selectionInspector"'), 'story editor should expose a right-side selected node inspector');
assert.ok(storyHtml.includes('id="autoLayoutButton"') && storyHtml.includes('id="reorderByCanvasButton"'), 'story editor should expose graph layout and canvas reorder actions');
assert.ok(storyJs.includes('selectedPointIndex') && storyJs.includes('selectedActionIndex'), 'story editor should track selected graph nodes and action nodes');
assert.ok(storyJs.includes('renderStoryGraph') && storyCss.includes('.story-graph-node'), 'story editor should render story points as canvas graph nodes');
assert.ok(storyJs.includes('startGraphNodeDrag') && storyJs.includes('reorderPointsByCanvas') && storyJs.includes('graphPosition'), 'story editor should support draggable node layout and canvas-based ordering');
assert.ok(storyJs.includes('startStoryCanvasPan') && storyJs.includes('focusSelectedOrAllStoryNodes') && storyJs.includes("event.key.toLowerCase() === 'f'"), 'story editor should support right/middle canvas panning and F focus');
assert.ok(storyCss.includes('.story-canvas') && storyCss.includes('.story-edges') && storyCss.includes('.story-edge-path'), 'story editor should style a grid canvas and connection lines');
assert.ok(storyCss.includes('.story-node-header') && storyCss.includes('.story-node-event'), 'story node cards should separate sequence summary from player-facing story event');
assert.ok(storyCss.includes('.story-action-node') && storyCss.includes('.story-action-edge-path'), 'story actions should render as child graph nodes below story points');
assert.ok(storyCss.includes('overflow-wrap: anywhere') && storyCss.includes('white-space: normal'), 'story graph node text should wrap instead of overflowing');
assert.ok(!storyCss.includes('#e34b32') && !storyCss.includes('#dfbd44'), 'story graph nodes should not keep rough red/yellow annotation borders');
assert.ok(storyJs.includes('previousProgressOptions') && storyJs.includes('ensureRecordProgressAction'), 'story editor should provide progress-key helpers for conditions');
assert.ok(storyJs.includes('inputTextVariants') && storyJs.includes('键鼠正文') && storyJs.includes('手柄正文'), 'story editor should support separate keyboard/mouse and gamepad copy variants');
assert.ok(storyJs.includes('useInputTextVariants') && storyJs.includes('区分键鼠/手柄正文') && storyJs.includes('checkboxInput'), 'story editor should gate input-specific copy behind an explicit action toggle');
assert.ok(storyJs.includes('undoEdit') && storyJs.includes('redoEdit') && storyJs.includes('pushHistorySnapshot'), 'story editor should support undo and redo history');
assert.ok(storyJs.includes("key === 'z'") && storyJs.includes("key === 'y'"), 'story editor should support keyboard undo and redo');
assert.ok(storyJs.includes('tutorialPages') && storyJs.includes('renderTutorialPagesEditor') && storyJs.includes('教程弹窗页'), 'story editor should support multi-page tutorial popup source data');
assert.ok(storyHtml.includes('id="editModal"') && storyHtml.includes('id="editModalContent"'), 'story editor should provide a modal editor for large node forms');
assert.ok(storyJs.includes('openEditModal') && storyJs.includes("addEventListener('dblclick'"), 'story graph nodes should open modal editing from double click');
assert.ok(storyJs.includes('node-edit-button') && storyCss.includes('.node-edit-button'), 'story graph nodes should expose an inline icon edit button');
assert.ok(storyJs.includes("action.type !== 'TutorialPopup'") && storyJs.includes('旧版 body 字段会保留'), 'tutorial popup actions should use page editor instead of ordinary body field');
assert.ok(storyJs.includes('actionStatus') && storyJs.includes('action-status-list') && storyJs.includes('返回动作列表'), 'story point detail should show compact action statuses before opening one action');
assert.ok(storyCss.includes('.action-status-row') && storyCss.includes('.action-status-badge'), 'story editor should style compact action status rows');
assert.ok(storyJs.includes('preservePanelScroll') && storyJs.includes('renderPointsPreservingInspector'), 'story editor should preserve inspector scroll for nested edits and history operations');
assert.ok(storyCss.includes('.checkbox-row'), 'story editor should style boolean action toggles');
assert.ok(storyCss.includes('.tutorial-pages-editor') && storyCss.includes('.tutorial-page-card'), 'story editor should style tutorial page editor cards');
assert.ok(storyJs.includes('动作节点 ID') && storyJs.includes('复用 Key'), 'story editor should expose reusable action-node metadata');
assert.ok(storyJs.includes('SetActorEnabled') && storyJs.includes('目标 Actor 名称') && storyJs.includes('启用关卡对象'), 'story editor should expose level actor show/hide story actions');
assert.ok(storyJs.includes('collapsedPoints') && storyJs.includes('collapsedActions'), 'story editor should track collapsed point and action cards');
assert.ok(storyJs.includes('pointCollapseKey') && storyJs.includes('actionCollapseKey'), 'story editor should use stable collapse keys');
assert.ok(storyJs.includes('makeCollapseButton') && storyJs.includes('setCollapseButtonState'), 'story editor should use arrow collapse buttons without full list rerender');
assert.ok(!storyJs.includes("toggle.textContent = isCollapsed ? '展开' : '折叠'"), 'collapse control should not use text buttons');
assert.ok(storyCss.includes('.multi-choice'), 'story editor should style multi-choice fields');
assert.ok(storyCss.includes('.field-label.has-help'), 'story editor should visually mark labels with hover help');
assert.ok(storyCss.includes('.collapsed-summary'), 'story editor should style collapsed summaries');
assert.ok(storyCss.includes('.collapse-button::before'), 'story editor should render arrow collapse controls');
assert.ok(storyCss.includes('.story-action-node') && storyCss.includes('.selection-inspector'), 'story editor should style graph action nodes and inspector');

console.log('ProductionGraph UI contract smoke passed');
